reports/urls.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from views import ListView_relatorios, CreateView_relatorios, DetailView_relatorios, UpdateView_relatorios, DeleteView_relatorios, ForReportJson
from django.conf.urls import patterns, include, url

import models


try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import *



from views import report, report_list


urlpatterns = patterns('',


    url( r'^add/$', 
        (CreateView_relatorios.as_view( model=models.relatorios)),
        {'acao': 'Criar'}, name = 'relatorios_create'),

    url( r'^get_element_for_report/(?P<pk>\d+)$', 
        (ForReportJson.as_view( model=models.relatorios)), name = 'for_report'),


    url( r'^(?P<pk>\d+)$', (DetailView_relatorios.as_view( model=models.relatorios )),
        {'media_saida': 'web',
        'reverso_update': 'relatorios_update',
        'reverso_delete': 'relatorios_delete',
        'reverso_list': 'relatorios_list'}, name = 'relatorios_detail'),

    url( r'^update/(?P<pk>\d+)$', (UpdateView_relatorios.as_view( model=models.relatorios, success_url = reverse_lazy('relatorios_list'))),
        {'media_saida': 'web',
        'reverso_update': 'relatorios_update',
        'reverso_delete': 'relatorios_delete',
        'reverso_list': 'relatorios_list',
        'acao': 'Editar', 'reverso_detail': 'relatorios_detail'}, name = 'relatorios_update'),


    url( r'^delete/(?P<pk>\d+)$', DeleteView_relatorios.as_view( model=models.relatorios, success_url = reverse_lazy('relatorios_list')),
        {'media_saida': 'web',
        'reverso_update': 'relatorios_update',
        'reverso_delete': 'relatorios_delete',
        'reverso_detail': 'relatorios_detail',
        'reverso_list': 'relatorios_list'}, name = 'relatorios_delete'),


    # URLS sem definicao de objeto manda para listagem
    url( r'^list/$', (ListView_relatorios.as_view( model=models.relatorios, paginate_by = 10 )),
        name = 'relatorios_list'),   

   
    url(r'^$', report_list, name='model_report_list'),
    url(r'^(?P<slug>[\w-]+)/$', report, name='model_report_view'),    
)

reports/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.db.models import Q
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User, Group
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType


from south.modelsinspector import add_introspection_rules
add_introspection_rules([], ["^relatorios\.models\.ListField"])

import ast

#http://brunorocha.org/python/django/django-listfield-e-separetedvaluesfield.html
class ListField(models.TextField):
    __metaclass__ = models.SubfieldBase
    description = "Stores a python list"

    def __init__(self, *args, **kwargs):
        super(ListField, self).__init__(*args, **kwargs)

    def to_python(self, value):
        if not value:
            value = []

        if isinstance(value, list):
            return value

        return ast.literal_eval(value)

    def get_prep_value(self, value):
        if value is None:
            return value

        return unicode(value)

    def value_to_string(self, obj):
        value = self._get_val_from_obj(obj)
        return self.get_db_prep_value(value)


# Store the fields of allowed models to generate reports.
class ReportsFields(models.Model):
    #model = 
    content_type = models.ForeignKey(ContentType, related_name='+', editable=False)
    internal_type = models.CharField(max_length=100, verbose_name=u'Field internal type', help_text=u'')
    field_dict = models.CharField(max_length=5000, verbose_name=u'Field Dictionary', help_text=u'')


# Create your models here.
class relatorios(models.Model):
    ctype = models.ForeignKey(ContentType, related_name='+', editable=False)
    title = models.CharField(max_length=100, verbose_name=u'Título do relatório', help_text=u'')
    created_by = models.ForeignKey(User, related_name='+', verbose_name=u'Criado por', editable=False, )

    select_fields = models.ManyToManyField(ReportsFields, verbose_name=u'Campos do relatório', related_name='select_fields')
    group_fields = models.ManyToManyField(ReportsFields, verbose_name=u'Campos agrupáveis', related_name='group_fields')
    filter_fields = models.ManyToManyField(ReportsFields, verbose_name=u'Campos filtraveis', related_name='filter_fields', blank=True, null=True)
    config_chart_fields = models.ManyToManyField(ReportsFields, verbose_name=u'Campos do grafico', related_name='config_chart_fields', blank=True, null=True)


    # Como pegar FK com base nos apps. Via ContentType:
    #http://stackoverflow.com/questions/6335986/how-can-i-restrict-djangos-genericforeignkey-to-a-list-of-models
    limit_apps = settings.LIMIT_APPS

    limit = models.Q()
    for la in limit_apps:
        limit = limit | models.Q( app_label=la[0], model=la[1] )

    
    sessao = models.ForeignKey(ContentType,verbose_name='Sessão',limit_choices_to=limit,null=True,blank=True,)
    object_id = models.PositiveIntegerField(verbose_name='related object',null=True,)
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    def __unicode__( self ):
        return '%s' % ( self.title )

    def get_absolute_url(self):
        return reverse('relatorios_detail', kwargs={'pk': self.pk})
    
    class Meta:
        verbose_name = "Relatorio"
        verbose_name_plural = "Relatorios"

    def meta(self):
        return self._meta        

    def get_fields(self):
        # Definir os campos que nao serao mostrados no DetailView
        # Deve ser o atributo name, do field do model
        exclui_campo_da_view = ("")
        list_of_tuples = []
        for field in relatorios._meta.fields:
            if not field.name in exclui_campo_da_view:
                # Esse nao consegue retornar o valor de FK
                #list_of_tuples.append((field.verbose_name, field.value_to_string(self)))
                list_of_tuples.append((field.verbose_name, getattr(self, field.name)))
        # Captura os valores dos campos relacionados m2m.
        #http://stackoverflow.com/questions/8474013/loop-in-manytomany-fields-in-django-model
        for field in relatorios._meta.many_to_many:
                if not field.name in exclui_campo_da_view:
                    m2m_field = getattr(self, field.name)   
                    concatenados = ', '.join([str(i) for i in m2m_field.all()])
                    list_of_tuples.append((field.verbose_name, concatenados))
        return list_of_tuples  



# Status de pedido que se aplicam ao plano Simples
GRP_OR_RPT_CHOICES = (
    ('grp', u'Grupo'),
    ('rpt', u'Relatório'),
)
OPER = (
    ('sum_column', u'Soma'),
    ('avg_column', u'Média'),
    ('count_column', u'Contagem'),    
)

class totalization_fields( models.Model):
    report = models.ForeignKey(relatorios, related_name='+', verbose_name=u'Relatório', editable=False, )

    totalization_field = models.CharField(max_length=100, verbose_name=u'Coluna', help_text=u'')
    group_or_report = models.CharField(
        'group_or_report',
        choices=GRP_OR_RPT_CHOICES,
        max_length=18,
    )
    operation = models.CharField(
        'operation',
        choices=OPER,
        max_length=18,
    )    

reports/templates/relatorios_confirm_delete.html
{% extends  "reports_base.html" %}

{% block content %}
        <div id='{{ object_name }}_incluir_elemento'>    
        
    <div class="container">
        <div class="page-header">
                <h1>  Excluir </h1>
        </div>

          <div class="col-lg-12">    
            <form
                    action  = '#'
                    method  = 'post' 
            >
                {% csrf_token %}
            
                    <p 
                        class = 'alert alert-warning'
                    >
                        Deseja excluir definitivamente: "{{object}}"? 
                    </p>
                    <input 
                        class = 'btn btn-danger'
                        type  = 'submit' 
                        value = 'Sim' 
                    />

                    <a  href  = {% url reverso_detail object.id %}
                        class = "btn btn-warning {{ ajax }}"
                        data-replace="#{{ object_name }}_incluir_elemento">N&atilde;o
                    </a>            
            </form>
          </div>
    </div>          
    </div>          
{% endblock %}

reports/templates/relatorios_form.html
{% extends  "reports_base.html" %}
 

{% block content %}
    <div class="container">
        <div class="page-header">
          <div class="row">
            <div class="col-lg-12">
                    <h1>{{ acao }} Relatório</h1>
                    <!--<h4>Sessão: {{ elemento.nome }}</h4>-->
            </div>
          </div>
        </div>

        <form id="grafico" method="POST" action="#">
        {% csrf_token %}

        <div class="row">
          <div class="col-lg-12"> 
                <h2>Sessão</h2>
                <p>Seleciona uma sessão para a qual você quer gerar relatórios.</p>
                {{ form.sessao }}
          </div>
        </div>
        <!-- Carrega Jquery checkbox fields  -->
        <div id='ResponseDiv'>
        </div>
        </form>
    </div>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.1.min.js"></script>

<script type="text/javascript">
    $(function(){
      // bind change event to select
      $('#id_sessao').on('change', function () {
            var url = $(this).val(); // get selected value
            $.ajax({
            url : '/app_reports/get_element_for_report/' + url,
            //data:{id: $(this).attr('id')},
            type: 'GET',
            success: function(data){
                //console.log(data)
                $('#ResponseDiv').html(data);
            }
        });
      });
    });
</script>

{% endblock %}

reports/templates/relatorios_form_json.html
{% block content %}

    <!-- Para o sortable -->
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
  <style>
    #select_fields1, #select_fields2, #group_fields1, #group_fields2, #filter_fields1, #filter_fields2, #config_chart_fields1, #config_chart_fields2 { list-style-type: none; margin: 0; padding: 0; float: left; margin-right: 1px; background: #eee; padding: 2px; width: 100%; margin-bottom:10px;}

    #select_fields1 li, #select_fields2 li, #group_fields1 li, #group_fields2 li, #filter_fields1 li, #filter_fields2 li, #config_chart_fields1 li, #config_chart_fields2 li { margin: 5px; padding: 3px; padding-left: 10px; padding-right: 10px; font-size: 1.0em; float: left; display: inline;}
  </style>


        <div class="row" style="padding-top:30px">
          <div class="col-lg-12"> 
                <h2> Título do relatorio </h2>
                <div style="color:red; padding-bottom: 0px; padding-top: 0px;"> * campo obrigatório</div>
                <p>Dê um nome para identificar o relatório.</p>
                {{ form.title }}
                <strong style="color:red">{{ form.title.errors.as_text }}</strong>


          </div>
        </div>

        <div class="row" style="padding-top:30px">
          <div class="col-lg-12"> 
                <h2>  Campos do relatorio </h2>
                <div style="color:red; padding-bottom: 15px; padding-top: 0px;"> * campo obrigatório</div>             
                <p>Selecione os campos que irão compor o relatório e ordene na ordem que as colunas serão apresentadas. São necessários dois campos no mínimo para a criação de um relatório.</p>


                <ul id="select_fields1" class="droptrue">
                    {% for f in fields %}
                    <li id="select_fields_({{ f.0 }}, {{ f.1 }})" class="ui-state-default">{{ f.1 }}</li>
                    {% endfor %}
                </ul>  
                <br>
                <strong style="color:red">{{ form.select_fields.errors.as_text }}</strong>
                <ul id="select_fields2" class="droptrue">

                </ul>

          </div>
        </div>

        <!--
        Os fields sao inicializados como hidden. 
        No form, somente o model selecionado altera o widget dos respectivos fields 
        para checkbox select multiple.
        -->
        <div class="row" style="padding-top:30px">
          <div class="col-lg-4"> 
                <h2>  Agrupar resultados </h2>
                <div style="color:red; padding-bottom: 0px; padding-top: 0px;"> * campo obrigatório</div>
                <p>Selecione os campos agrupáveis no relatório.</p>
                {{ form.group_fields }}
                <strong style="color:red">{{ form.group_fields.errors.as_text }}</strong>

          </div>
          <div class="col-lg-4"> 
                <h2>  Filtrar resultados </h2>
                <p>Selecione os campos filtráveis no relatório.</p>
                {{ form.filter_fields }}               
                <strong style="color:red">{{ form.filter_fields.errors.as_text }}</strong>

          </div>
          <div class="col-lg-4"> 
                <h2>  Configurar gráfico </h2>
                <p>Selecione os campos apresentáveis nos gráficos.</p>
                {{ form.config_chart_fields }}             
                <strong style="color:red">{{ form.config_chart_fields.errors.as_text }}</strong>
            
          </div>
        </div> 


        <div class="row" style="padding-top:30px">
          <div class="col-lg-8"> 
                <h2>  Campos de somatória </h2>
                <strong style="color:red">{{ ts_fs.errors.as_text }}</strong>
                <p>
                <table class="table table-striped table-hover ">
                  <thead>
                    <th>Campo</th><th>Grupo/Relatório</th><th>Operação</th>
                  </thead>
                      {{ totalization_fields.management_form }}
                      {% for form in totalization_fields %}
                  <tr>
                      {{ form.id }}
                          <td>{{ form.totalization_field }}</td>
                          <td>{{ form.group_or_report }}</td>
                          <td>{{ form.operation }}</td>            
                  </tr>
                      {% endfor %}
                </table>
              </p>
          </div>  
        </div>

      </div> 


        <div class="row" style="padding-top:30px">
          <div class="col-lg-12" style="text-align:right"> 
                <input type='hidden' name='select_fields' id='select_fields'>
                <input type='hidden' name='ctype_id' value="{{ ctype }}">
                <a class = 'btn btn-warning' href = "javascript:history.back(-1);">
                    Voltar
                </a>
                <button type='submit' class="btn btn-success">Gravar</button>
          </div>
        </div>

    <script>
      $(function() {
        $( "ul.droptrue" ).sortable({
          connectWith: "ul"
        });
     
        $( "ul.dropfalse" ).sortable({
          connectWith: "ul",
          dropOnEmpty: false
        });
     
        $( "#select_fields1, #select_fields2, #group_fields1, #group_fields2, #filter_fields1, #filter_fields2, #config_chart_fields1, #config_chart_fields2" ).disableSelection();
      });
    </script>
    <script>
    // $( "#grafico" ).submit(function(){
    //   console.log('Select Fields:  ' + $( "#select_fields2" ).sortable("serialize"))
    //     console.log('Select Fields:  ' + $( "#select_fields2" ).sortable("serialize").toString())
    //     $('#select_fields').val($( "#select_fields2" ).sortable("serialize"));
    //     //return false;
    // }); 
    </script>   

<script>
    $( "#grafico" ).submit(function( event ) {  

      console.log('Select Fields:  ' + $( "#select_fields2" ).sortable("serialize"))
      console.log('Select Fields:  ' + $( "#select_fields2" ).sortable("serialize").toString())
      $('#select_fields').val($( "#select_fields2" ).sortable("serialize"));

      // Stop form from submitting normally
      event.preventDefault();

      var data = $('form').serialize();
      var url = '/app_reports/add/'
      var posting = $.post(url, data);
     
      posting.done(function( data ) {
        $( "#ResponseDiv" ).empty().append(  $( data ) );
      });
    });
</script>


{% endblock %}

reports/templates/relatorios_update_form.html
{% extends  "reports_base.html" %}

{% block content %}
    <!-- Para o sortable -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
  <style>
    #select_fields1, #select_fields2, #group_fields1, #group_fields2, #filter_fields1, #filter_fields2, #config_chart_fields1, #config_chart_fields2 { list-style-type: none; margin: 0; padding: 0; float: left; margin-right: 1px; background: #eee; padding: 2px; width: 100%; margin-bottom:10px;}

    #select_fields1 li, #select_fields2 li, #group_fields1 li, #group_fields2 li, #filter_fields1 li, #filter_fields2 li, #config_chart_fields1 li, #config_chart_fields2 li { margin: 5px; padding: 3px; padding-left: 10px; padding-right: 10px; font-size: 1.0em; float: left; display: inline;}
  </style>

    <div class="container">
     <div class="bs-docs-section">
        <div class="page-header">
          <div class="row">
            <div class="col-lg-12">
                <h1>Edição de Relatórios</h1>
                <p>Relatório para a sessão "{{ ct.name }}"</p>
            </div>
          </div>
        </div>

        <form id="grafico" method="POST" action="#">
        {% csrf_token %}        
        
        <div class="row">
          <div class="col-lg-12"> 
                <h2> Título do relatorio </h2>
                <p>Dê um nome para identificar o relatório.</p>
                {{ form.title }}
                <br>
                <strong style="color:red">{{ form.title.errors.as_text }}</strong>

                <h2>  Campos do relatorio </h2>
                <p>Selecione os campos que irão compor o relatório e ordene na ordem que as colunas serão apresentadas. São necessários dois campos no mínimo para a criação de um relatório.</p>

                <ul id="select_fields1" class="droptrue">
                    {% for f in fields %}
                    <li id="select_fields_({{ f.0 }}, {{ f.1 }})" class="ui-state-default">{{ f.1 }}</li>
                    {% endfor %}
                </ul>  
                <br>
                <strong style="color:red">{{ form.select_fields.errors.as_text }}</strong>
                <ul id="select_fields2" class="droptrue">
                    {% for sf in select_fields %}
                    <li id="select_fields_({{ sf.0 }},{{ sf.1 }})" class="ui-state-default">{{ sf.1 }}</li>
                    {% endfor %}
                </ul>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-4"> 
                <h2>  Agrupar resultados </h2>
                <p>Selecione os campos agrupáveis no relatório.</p>
                {{ form.group_fields }}
          </div>
          <div class="col-lg-4"> 
                <h2>  Filtrar resultados </h2>
                <p>Selecione os campos filtráveis no relatório.</p>
                {{ form.filter_fields }}

          </div>
          <div class="col-lg-4"> 
                <h2>  Configurar gráfico </h2>
                <p>Selecione os campos apresentáveis nos gráficos.</p>
                {{ form.config_chart_fields }}
          </div>
        </div> 

        <div class="row">
          <div class="col-lg-8"> 
                <h2>  Campos de somatória </h2>
                <strong style="color:red">{{ tf.errors.as_text }}</strong>
                <p>
                <table class="table table-striped table-hover ">
                  <thead>
                      <th>Campo</th><th>Grupo/Relatório</th><th>Operação</th><th>Excluir</th>
                  </thead>
                      {{ tf.management_form }}
                      {% for form in tf %}
                  <tr>
                      {{ form.id }}
                      <td>{{ form.totalization_field }}</td>
                      <td>{{ form.group_or_report }}</td>
                      <td>{{ form.operation }}</td>       
                      <td>{{ form.DELETE }}</td>       
                  </tr>
                      {% endfor %}
                </table>
              </p>
          </div>  
        </div>


        <div class="row">
          <div class="col-lg-12" style="text-align:right"> 
                <input type='hidden' name='select_fields' id='select_fields'>
                <input type='hidden' name='ctype_id' value="{{ ct.id }}">
                <a class = 'btn btn-warning' href = "javascript:history.back(-1);">
                    Voltar
                </a>
                <button type='submit' class="btn btn-success">Gravar</button>
          </div>
        </div>
        </div>
        </form>
      </div>
    </div>




    <!--
    <script src="/static_files/inteliform/jquery/jquery-ui.js"></script>
    -->

    
    <script>
      $(function() {
        $( "ul.droptrue" ).sortable({
          connectWith: "ul"
        });
     
        $( "ul.dropfalse" ).sortable({
          connectWith: "ul",
          dropOnEmpty: false
        });
     
        $( "#select_fields1, #select_fields2, #group_fields1, #group_fields2, #filter_fields1, #filter_fields2, #config_chart_fields1, #config_chart_fields2" ).disableSelection();
      });
    </script>
    <script>
    $( "#grafico" ).submit(function(){
      console.log('Select Fields:  ' + $( "#select_fields2" ).sortable("serialize"))
        console.log('Select Fields:  ' + $( "#select_fields2" ).sortable("serialize").toString())
        $('#select_fields').val($( "#select_fields2" ).sortable("serialize"));
        //return false;
    }); 
    </script>   








{% endblock %}

reports/templates/reports_base.html
{% extends  "base_painel_admin.html" %}

{% block app.scripts %}

    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.1.min.js"></script>

    <script src="https://code.jquery.com/ui/1.11.1/jquery-ui.min.js" type="text/javascript"></script>

    
{% endblock %}

reports/templates/reports_detail.html
{% extends  "reports_base.html" %}
 

{% block content %}
<div class="container">

        <div class="page-header">
          <div class="row">
              <h1 id="buttons">{{object.meta.verbose_name}}</h1>
          </div>
        </div>



<table class = 'table table-condensed' >

{% comment %}
Metodo get_fields estah definido nos models de cada app.
{% endcomment %}
    
{% for name, value in object.get_fields %}
    <tr>
        <td>
            <b> {{ name }} </b>
        </td>
        <td>
            {{ value }}
        </td>
    </tr>
    {% endfor %}
</table>



{% if object.get_update_url %}
    <a 
        class = 'btn btn-info'
        href  = '{{object.get_update_url}}'
    >
        Editar
    </a>
{% endif %}
{% if object.get_delete_url %}
    <a 
        class = 'btn btn-warning'
        href  = '{{object.get_delete_url}}'
    >
        Apagar
    </a>
{% endif %}

{% comment %}
    <a 
        class = 'btn btn-success'
        href  = '{% url 'relatorios_list' sistema='sistema' sistema_id=object.sistema.id %}'
    >
{% endcomment %}

    <a 
        class = 'btn btn-success'
        href  = '{% url 'relatorios_list' %}'
    >

        Listar todos
    </a>





</div>
{% endblock %}

reports/templates/reports_list.html
{% extends  "reports_base.html" %}

 
{% block content %}



    <div class="container">
     <div class="bs-docs-section">
        <div class="page-header">
          <div class="row">
            <div class="col-lg-12">
                <h1>Relatórios cadastrados</h1>
            </div>
          </div>
        </div>

        
        <div class="row">
          <div class="col-lg-12">    
            <table class = 'table table-striped'>
                    <thead>
                        <th> ID </th>
                        <th> Elemento </th>
                        <th> Nome do Relatório </th>
                        <th> Editar </th>
                        <th> Apagar </th>
                    </thead>
            
                    {% for object in object_list %}
                    <tr>
                        <td> 
                            {{ object.id }} 
                        </td>
                        <td> 
                            {{ object.ctype }} 
                        </td>                                                
                        <td> 
                            <a
                                href  = '../report/?id={{ object.id }}'
                            >                            
                            {{object.title}} 
                            </a>                        
                        </td>
                        <td>
                            <a
                                href  = '{% url 'relatorios_update' object.id %}'
                            >
                                Editar
                            </a>                        
                        </td>
                        <td>
                            <a
                                href  = '{% url 'relatorios_delete' object.id %}'
                            >
                                Apagar
                            </a>                        
                        </td>
                        <td>
                            {% comment %}

                            <a
                                href  = '{{object.get_absolute_url}}'
                            >
                                Ir
                            </a>

                            <a
                                href  = '../report/?id={{ object.id }}'
                            >
                                Ir
                            </a>                            
                            {% endcomment %}

                        </td>
                    </tr>
                    {% endfor %}
            
            </table>
            
            



            {% comment %}                
            {% if object_list.model.get_create_url %}
            <div class = 'span4'>
            <a class = 'btn btn-primary' href  = '{{object_list.model.get_create_url }}'>
                Criar novo relatório
            </a>
            </div>
            {% endif %}
            {% endcomment %}  

            
            <div class = 'span4'>
            <a class = 'btn btn-primary' href  = '{% url 'relatorios_create' %}'>
                Criar novo relatório
            </a>
            </div>




            
            <div class = 'span4'>
            {% if page_obj.has_previous %}
                <a class = 'btn btn-info' href="?page={{ page_obj.previous_page_number}}"> Anterior</a>
            {% endif %}
            {% if page_obj.has_next %}
                <a class = 'btn btn-info' href="?page={{ page_obj.next_page_number}}"> Próxima</a>
            {% endif %}
            </div>
            

          </div>
        </div>
{% endblock %}